### ISSUE TITLE
Decide how to handle Chapter 1 process hanging issue

### ISSUE THREAD

**Issue by BuckeyeCoder** [jonegil/gui-with-gio#13]
_This is a copypasta from #12 and I'm moving it to an issue because I don't want it to get lost.  I think we need to decide what to do, if anything. Until I understand your direction a bit more I feel uncomfortable suggesting which way to go._

The demo at the end of Chapter 1 does not contain an os.Exit(0) line. When the student clicks the window frame's X to exit the app, the window goes away but the process still hangs in the terminal.

Now, you may know that already and it may be intentional for all I know. If it is, I agree with your call, because I'm pretty sure the added complexity to get the os.Exit(0) line into the right place would defeat the goal of keeping this chapter SIMPLE.

BUT, if that IS your reason then my opinion is that you need to do an "information" or "warning" callout at the end of the chapter. The hung process looks bad and makes the project look bad for producing a "failed" demo. Providing just a sentence or two telling the student that "its intentional" and to use ctrl-c to exit the process eliminates this negative "broken" vibe.

**Comment by jonegil** [comment]
Interesting, and not intentional, so thanks for spotting. 

Without deep thought I'm leaning towards leaving it out in Ch 1, to make it as bare minimum as possible. Maybe mention in text. But Ch 2 onwards should definetely fix it.

**Comment by jonegil** [comment]
Rechecking on my Mac, this is not an issue. What's your platform?

**Comment by BuckeyeCoder** [comment]
That's very interesting! My environment is Linux Mint, running it in a terminal inside VSCode. The command line never returns even though the window is closed via the window frame x icon.Maybe we should get Chris to chime in here? ---- On Sat, 18 Dec 2021 14:36:33 -0500  ***@***.***  wrote ----
Rechecking on my Mac, this is not an issue. What's your platform?

**Comment by jonegil** [comment]
Got a linux box here and a windows box there, and can cross check.

**Comment by jonegil** [comment]
When fixing the issues with the new version, it was a good occasion to also add the os.Exit(). Done for all chapters now. Thanks for pointing out, better now.
