### ISSUE TITLE
undefined: clip.Circle

### ISSUE THREAD

**Issue by StrawberryChocolateFudge** [jonegil/gui-with-gio#18]
Hi, I'm doing these tutorials, they are great.

But I think they are out of date, the Circle has been removed from the package gioui.org/op/clip
here:
https://github.com/gioui/gio/commit/6534639276d7536b223b56326130f0c68a5e8278

**Comment by jonegil** [comment]
Hey mate, thanks for raising the issue!

Let me have a look. 

Ps, love your github name by the way!

**Comment by StrawberryChocolateFudge** [comment]
yeah! It's awesome. Thanks

**Comment by jonegil** [comment]
Great, thanks for reporting back
