### ISSUE TITLE
Add a License file

### ISSUE THREAD

**Issue by BrianTehOwnerer** [jonegil/gui-with-gio#31]
Add a license file such as GPL or MIT so that others can have their code from your tutorial series on github.
Without that license its debatable if they can legally be used or shared on github.

Thanks for the great tutorial by the way!

**Comment by jonegil** [comment]
Hi Brian. Hope you found it useful, would be great to see what you're building. 

As for license, I've now added one, and use the same as GIO itself, MIT/Unlicense.
