### ISSUE TITLE
The Chapter 10 missed some part of codes

### ISSUE THREAD

**Issue by miry** [jonegil/gui-with-gio#4]
Tutorial: Egg Timer
Page: Input Boiltime
Link : https://github.com/jonegil/gui-with-gio/blob/main/egg_timer/10_input_boiltime.md

I tried to follow the Chapter 10. There are missed code lines in section `2. The editor widget`:

1. There is no clear how `boilDuration`  is initialized. I assume it is extracted number from string  `boilDurationInput`.
2. There are some notes/comments how layouts are done, but there is no code for it.

**Comment by jonegil** [comment]
Interesting, let me investigate.

**Comment by jonegil** [comment]
Have a look now. I have expanded this chapter with more details on both the boilDuration and the inputbox. 

Also I've adjusted the code slightly, to hopefully make it a little clearer. Have a look at both and I hope it works.
