### ISSUE TITLE
Understand the flexbox's layout

### ISSUE THREAD

**Issue by bagualing** [jonegil/gui-with-gio#46]
Please check out the picture below. In Chapter 4, I'm trying to understand the flexbox's layout—am I getting it right? If not, please let me know! Thanks!

![egg](https://github.com/user-attachments/assets/db86d768-aade-449a-8e64-335f20bb05a9)

**Comment by jonegil** [comment]
Sorry for The late response, let me have a look

**Comment by jonegil** [comment]
First of all, thank you for your interest. And wow, what a great question, you recalled phrased it well.

The button size is effectively decided by itself, with variables set in ButtonStyle. 

See f.ex here. https://git.sr.ht/~eliasnaur/gio/tree/v0.7.1/widget/material/button.go#L53

The white at the top is whatever is leftover after the tho explicit rigids have been placed first. So it looks to me that your understanding is fine.

**Comment by bagualing** [comment]
@jonegil Thank you for your reply. Now it's clear.
